kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    net.gorinsky/app: test-deploy-1
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
